// FLAGS
#define DRAW_RADIUS_FLAG true
#define DRAW_VECTOR_FLAG true

// CONSTANTS
#define WIDTH 640
#define HEIGHT 480
#define TITLE "Networked Boids"

#define NUM_BOIDS 10
#define BOID_RADIUS 120
#define SEPERATION_RADIUS 40

#define BOID_WIDTH 30
#define BOID_HEIGHT 15

#define COHESION_WEIGHT 0.01
#define SEPARATION_WEIGHT 0.09
#define ALIGNMENT_WEIGHT 0.9

#define PI 3.1415
#define TICK 10
#define TURN_INCREMENT PI/180